spring.profiles.active: ${VPROFILE:local}

server:
  display-name: ${VHOSTNAME:${HOSTNAME}}
  port: ${VPORT:8761}
  
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: true
    waitTimeInMsWhenSyncEmpty: 0

    
security:
  basic:
    enabled: false
  user:
    name: ${VEUREKAUSER:eurekaconfig}
    password: ${VEUREKAPASSWD:eurekapasswd}
    
spring:
  user:
    roles: ACTUATOR
  cloud:
    config:
      discovery:
        enabled: true
      uri: config
      server:
        prefix: /config
        git:
          uri: ${VGITCONFIGURL}

---
spring:
  profiles: local

  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitkshirsagar13/spring-config.git
