spring.profiles.active: ${VPROFILE:native}

server:
  context-path: /${VCONTEXTPATH:registry}
  display-name: ${VHOSTNAME:${HOSTNAME}}
  port: ${VPORT:8761}
  
eureka:
  instance:
    hostname: ${HOSTNAME}
    instanceId: ${HOSTNAME:localhost.shinigami.io}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    service-url: 
      defaultZone: http://localhost.shinigami.io:${server.port}/registry/eureka
    registerWithEureka: false
    fetchRegistry: false
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: true
    waitTimeInMsWhenSyncEmpty: 0

    
security:
  basic:
    enabled: false
  user:
    name: ${VEUREKAUSER:eurekaconfig}
    password: ${VEUREKAPASSWD:eurekapasswd}

management:
  context-path: /admin
  security:
    enabled: true
    
spring:
  user:
    roles: ACTUATOR
  cloud:
    config:
      discovery:
        enabled: true
      uri: config
      server:
        prefix: /config
        native:
          search-locations: classpath:spring-config-master/
        git:
          uri: ${VGITCONFIGURL:https://github.com/amitkshirsagar13/spring-config.git}
